services:
  - type: web
    name: cancer-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn cancer_app.app:app"
    envVars: []
    runtime: python-3.10.13
